version: "3.8"
services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - cafe-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - menu-service
      - order-service
      - payment-service
      - inventory-service
      - customer-service
    networks:
      - cafe-network

  menu-service:
    build: ./menu-services
    depends_on:
      - mongodb
    networks:
      - cafe-network

  order-service:
    build: ./order-services
    depends_on:
      - mongodb
      - menu-service
      - inventory-service
      - customer-service
    networks:
      - cafe-network

  payment-service:
    build: ./payment-services
    depends_on:
      - mongodb
      - order-service
    networks:
      - cafe-network

  inventory-service:
    build: ./inventory-services
    depends_on:
      - mongodb
    networks:
      - cafe-network

  customer-service:
    build: ./customer-services
    depends_on:
      - mongodb
    networks:
      - cafe-network

networks:
  cafe-network:
    driver: bridge

volumes:
  mongo-data:
